Fetching data from an API based on the provided API link
VeroCodingProjects/postman pull request #5
Opened 2023-06-17 15:12 UTC by VeroCodingProjects

2023-06-17 15:41 UTC, Daniel-Tanase requested changes

2023-06-17 15:41 UTC, Daniel-Tanase commented on api/api.js
> +/**
Let's be consistent and use only `.ts`

2023-06-17 15:41 UTC, Daniel-Tanase commented on pages/index.tsx
> +        <InputField></InputField>
You can simply use `<InputField/>`

2023-06-17 15:41 UTC, Daniel-Tanase commented on api/api.js
> + * FetchData Function
Also, try to get rid of this file

2023-06-17 15:41 UTC, Daniel-Tanase commented on components/input/InputField.tsx
> +  const [apiLink, setApiLink] = useState('');
Move the logic to the page, there should be only the component itself with the parameters.
Look [here](https://github.com/Daniel-Tanase/docskeepcoding/blob/main/components/utils/inputs/text/TextInput.tsx) for an example.

2023-06-17 15:41 UTC, Daniel-Tanase commented on pages/_app.tsx
> +import '/home/vero_romanescu/postman/public/styles/global.css';
The import is relative, so you can simply go from here: `../public/styles/global.css`

2023-06-17 15:41 UTC, Daniel-Tanase commented on pages/_app.tsx
>  export default function App({ Component, pageProps }: AppProps) {
Is recommended to declare the types, so it would be something like: `pageProps: { session, ...pageProps } `

2023-06-17 15:41 UTC, Daniel-Tanase commented on public/styles/global.css
> +#search-box {
Use `class` for CSS

2023-06-19 17:35 UTC, Daniel-Tanase requested changes

2023-06-19 17:35 UTC, Daniel-Tanase commented on components/input/InputField.tsx
> +import { TextField } from '@mui/material';
I think you have to rename this file, because is not only a "input field"

2023-06-19 17:35 UTC, Daniel-Tanase commented on pages/index.tsx
> + * The component consists of a request type selector, an API link input field, and a button to fetch data.
In not a component, is a page, also, make sure you don't go over 80 characters even in comments

2023-06-19 17:35 UTC, Daniel-Tanase commented on pages/index.tsx
> +    if (!apiLink) {
Can you get rid of this "if"?

2023-06-19 17:35 UTC, Daniel-Tanase commented on pages/index.tsx
> +      console.error('Error fetching data:', error);
Let's add a `// TODO: ...` comment here for the future you will need to show the error to the user.

2023-06-19 17:35 UTC, Daniel-Tanase commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "api/api.ts"],
the `api/api.ts` file is no longer in the project, so you don't need this configuration change here.

2023-06-20 20:13 UTC, VeroCodingProjects commented on pages/index.tsx
> +    if (!apiLink) {
Yes, I did it by having 'required' attribute in te TextField tag

2023-06-20 20:32 UTC, Daniel-Tanase requested changes

2023-06-20 20:32 UTC, Daniel-Tanase commented on pages/index.tsx
> +                setRequest(event.target.value as string)
use `String(event.target.value)`

2023-06-21 07:21 UTC, merged